# Generated by Django 4.2.2 on 2023-07-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('stock', models.FloatField()),
                ('unit', models.IntegerField(choices=[('Kg', 'Kilos'), ('Lts', 'Litros'), ('Paq', 'Paquete'), ('Un', 'Unidad')])),
                ('largo', models.FloatField()),
                ('ancho', models.FloatField()),
                ('peso', models.FloatField()),
                ('color', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
