# Generated by Django 4.0.5 on 2023-07-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, choices=[('F', 'Fiat'), ('C', 'Chevrolet'), ('F', 'Ford'), ('T', 'Toyota')], default='Ford', max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('serial_carroceria', models.CharField(max_length=50)),
                ('serial_motor', models.CharField(max_length=50)),
                ('categoria', models.CharField(blank=True, choices=[('P', 'Particular'), ('T', 'Transporte'), ('C', 'Carga')], default='Particular', max_length=20)),
                ('precio', models.FloatField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['marca', 'modelo'],
            },
        ),
    ]
