# Generated by Django 4.0.5 on 2023-07-18 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculo', '0003_alter_vehiculo_categoria_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
