# Generated by Django 4.2.2 on 2023-07-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Activo'), ('m', 'Mantenimiento'), ('r', 'Reservado')], default='a', max_length=1),
        ),
    ]
