# Generated by Django 4.2.2 on 2023-07-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('M', 'Mantenimiento'), ('R', 'Reservado')], default='a', max_length=1),
        ),
    ]
