# Generated by Django 4.2.2 on 2023-07-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['titulo', 'editorial']},
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='state',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('M', 'Mantenimiento'), ('R', 'Reservado')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, choices=[('E', 'Empastado'), ('D', 'Digital')], default='E', max_length=1),
        ),
    ]
