# Generated by Django 4.2.2 on 2023-07-04 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_options_remove_book_status_book_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['titulo', 'editorial', 'state']},
        ),
    ]
