# Generated by Django 4.2.2 on 2023-07-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_preferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='preferencia',
            field=models.CharField(blank=True, choices=[(1, 'Azul'), (2, 'Negro'), (3, 'Blanco'), (4, 'Gris')], default='', max_length=200),
        ),
    ]
